"""refactor models

Revision ID: 0c150ad75857
Revises: cdf7f399e4ea
Create Date: 2025-07-31 00:05:24.098464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c150ad75857'
down_revision: Union[str, Sequence[str], None] = 'cdf7f399e4ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('objs', sa.Column('ctgr_b', sa.String(), nullable=False))
    op.add_column('objs', sa.Column('etpr', sa.DateTime(), nullable=False))
    op.add_column('objs', sa.Column('ltpr', sa.DateTime(), nullable=False))
    op.alter_column('objs', 'ctgr',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('objs_ctgr_fkey'), 'objs', type_='foreignkey')
    op.create_foreign_key(None, 'objs', 'sbjs', ['ctgr_b'], ['ctgr_b'])
    op.drop_column('objs', 'tpr')
    op.add_column('sbjs', sa.Column('ctgr_b', sa.String(), nullable=False))
    op.add_column('sbjs', sa.Column('etpr', sa.String(), nullable=False))
    op.add_column('sbjs', sa.Column('ltpr', sa.DateTime(), nullable=False))
    op.alter_column('sbjs', 'ctgr',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('sbjs_ctgr_key'), 'sbjs', type_='unique')
    op.create_unique_constraint(None, 'sbjs', ['ctgr_b'])
    op.drop_column('sbjs', 'tpr')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sbjs', sa.Column('tpr', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sbjs', type_='unique')
    op.create_unique_constraint(op.f('sbjs_ctgr_key'), 'sbjs', ['ctgr'], postgresql_nulls_not_distinct=False)
    op.alter_column('sbjs', 'ctgr',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('sbjs', 'ltpr')
    op.drop_column('sbjs', 'etpr')
    op.drop_column('sbjs', 'ctgr_b')
    op.add_column('objs', sa.Column('tpr', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'objs', type_='foreignkey')
    op.create_foreign_key(op.f('objs_ctgr_fkey'), 'objs', 'sbjs', ['ctgr'], ['ctgr'])
    op.alter_column('objs', 'ctgr',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('objs', 'ltpr')
    op.drop_column('objs', 'etpr')
    op.drop_column('objs', 'ctgr_b')
    # ### end Alembic commands ###
